title: Free Thinker
description: >
  Um site para organizar os conteúdos das disciplinas de Física.
baseurl: "/free-thinker" # use esta linha para definir o subdiretório
url:  # ajuste para o seu URL de produção quando necessário

markdown: kramdown
kramdown:

  math_engine: mathjax
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - LICENSE
  - Makefile
  - package.json
  - package-lock.json
