title: "Free Thinker"
baseurl: "/free-thinker"  # Esta é a chave para evitar repetir o prefixo
url: "https://nzinga-nuru.github.io"
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
permalink: /:categories/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-mathjax
mathjax:
  path: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
collections:
  cursos:
    output: true
paginate: 5
paginate_path: "/page:num"
theme: minima
relative_permalinks: false
