title: Free Thinker
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Portal para cursos de Física.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nzinga-nuru.github.io/free-thinker" # the base hostname & protocol for your site
twitter_username: your-twitter-handle
github_username: your-github-username

theme: minima

plugins:
  - jekyll-feed

collections:
  cursos:
    output: true
