title: Free Thinker
description: >- # Descrição
  Site para cursos de física
baseurl: "/free-thinker" # não use '/' no final
url: "https://nzinga-nuru.github.io/" # URL do seu site no GitHub Pages
theme: minima

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    block:
      line_numbers: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
